### ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
### Brand API
### ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

### Create Brand
POST http://localhost:8080/api/brands
Content-Type: application/json

{
  "slug": "some-brand-slug",
  "name": "Some Brand Name",
  "description": "Some Brand Description"
}

### Read Brand
GET http://localhost:8080/api/brands/some-brand-slug
Accept: application/json

### ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
### Category API
### ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

### Create Parent Category
POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "slug": "some-parent-category-slug",
  "name": "Some Parent Category Name",
  "description": "Some Parent Category Description"
}

### Create Child Category
POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "slug": "some-parent-category-slug/some-child-category-slug",
  "name": "Some Child Category Name",
  "description": "Some Child Category Description"
}

### Read Parent Category
GET http://localhost:8080/api/categories/some-parent-category-slug
Accept: application/json

### Read Child Category
GET http://localhost:8080/api/categories/some-parent-category-slug/some-child-category-slug
Accept: application/json

### ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
### Product API
### ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

### Create Product
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "slug": "some-product-slug",
  "name": "Some Product",
  "description": "Some product description",
  "brandSlug": "some-brand-slug",
  "categorySlug": "some-parent-category-slug/some-child-category-slug"
}

### Read Product
GET http://localhost:8080/api/products/some-product-slug
Accept: application/json